server:
  port: 8989
spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'productdb'
app:
  jwt:
    secret: 'abcdefghijklmnOPQRSTUVWXYZ'
    expire_duration: 86400000



